/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define NVIC_ISER0 0xE000E100
#define NVIC_ISPR0 0XE000E200
#define NVIC_IPR0  0xE000E400
#define IRQNo_Timer2 28
#define IRQNo_I2C1 31


uint32_t *pISPR0 = (uint32_t*) NVIC_ISPR0;

void configure_priority_for_interrupt(uint8_t irqno  , uint8_t priority)
{


	// calculate the correct register for priority with the base address
	uint32_t *pIPR = (uint32_t*) NVIC_IPR0 + (uint32_t)(irqno / 4 );


	//calculate the number of bits to place the priority in the correct position

    uint8_t bitshift = (irqno % 4) * 8;

    //first clear the byte for irqno priority

    *pIPR &= ~(0xFF << (bitshift));

    *pIPR |= (priority << (bitshift));

}

int main(void)
{
    /* Loop forever */



	// Configure the priority for the peripherals
	configure_priority_for_interrupt(IRQNo_Timer2, 0x60);
	configure_priority_for_interrupt(IRQNo_I2C1, 0x50);

	// Enable the IRQ  in NVIC
	uint32_t *pISER0 = (uint32_t*) NVIC_ISER0 ;

	*pISER0 |= (1<< (IRQNo_I2C1 % 32)) | (1 << (IRQNo_Timer2 % 32));


	//Set the interrupt pending bit in NVIC pending register



	//*pISPR0 |= (1<< (IRQNo_I2C1 % 32)) | (1 << (IRQNo_Timer2 % 32));

	*pISPR0 |=  (1 << (IRQNo_Timer2 % 32));

	for(int i =0 ; i < 1000 ;i++)
		{
   			continue;
		}






	for(;;);
}


void TIM2_IRQHandler(void)
{
	printf("Here");
	*pISPR0 |= (1<< (IRQNo_I2C1 % 32)) ;

	for(int i =0 ; i < 1000 ;i++)
		{
			continue;
		}
}
void I2C1_EV_IRQHandler(void)
{
	printf("also here");
}
