/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#define BIT_BASE_ADDR 0x20000000
#define BIT_ALIAS_BASE_ADDR 0x22000000
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	uint8_t * ptr =(uint8_t*) 0x20000200;
	*ptr |= (1<<7);

	*ptr &= ~(1<<7);

    int *bit_band_alias =(int *) (BIT_ALIAS_BASE_ADDR + (32* (0x20000200 - BIT_BASE_ADDR)) + (7 * 4) );
    *bit_band_alias = 1;





	for(;;);
}
